[package]
name = "dfs-mount"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
fuser = "0.15"
libc = "0.2"   
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
md-5 = "0.10"
rand = "0.9"
async-trait = "0.1"
dfs-common = { path = "../common" }
